### ISSUE TITLE
not an issue : assembler options

### ISSUE THREAD

**Issue by theflynn49** [nihirash/Agon-rokky#2]
Hello.
For it to re-assemble properly, I need to pass the "-b 00" option to ez80asm, or else the header 0x00-0x40 is wrongly filled with 0xFF bytes and MOS gets confused. Maybe my version of ez80asm I don't know, or something I missed ;)

**Comment by nihirash** [comment]
Older versions didn't required that. 

I should update readme for more actual build info.

**Comment by theflynn49** [comment]
Thank you for your fast reply !
No, no, Please ignore this comment of mine. I was confused, not MOS. It works with both filling bytes, 0x00 or 0xFF, and probably anything else. I close this issue.
The fact is that my version of ez80asm fills the header with 0xFF, and your version fills the header with zeroes.
