### ISSUE TITLE
The program freezes during loading

### ISSUE THREAD

**Issue by csabibela** [nihirash/Agon-rokky#3]
The loading stops after the 'Sending bitmaps to VDP' message.  The MOS and VDP versions are 1.04 RC2.

**Comment by nihirash** [comment]
Hello!

There was some changes on VDP side and for fixing this issue you should try make next steps:
 * In Arduino IDE - update ESP32 Board Manager to 2.0.14 and ESP32Time to 2.0.4
 * Fetch latest VDP from github - it still will have 1.04 RC2 version but have fixes. 
 * Flash new firmware and try version adopted for new changes(video modes changed): https://github.com/nihirash/Agon-rokky/tree/main/bin/1.04%2B

I wish it helps you!

**Comment by csabibela** [comment]
Thank you, it's working well now.
