### ISSUE TITLE
Hang on start

### ISSUE THREAD

**Issue by appndownUG** [nihirash/Agon-rokky#4]
I have Version 1.04 RC2 MOS & VDP.
The Game starts...
Very Important..
Video Mode...
Setting key....
Sending Bitmap to...

and then nothing.  It hangs... What i make wrong ?

**Comment by nihirash** [comment]
There was similar issue report and check my response here: https://github.com/nihirash/Agon-rokky/issues/3#issuecomment-1773856265

There're instruction about updating VDP - there couple important points(about library versions). 

If there will be another issues - please write me and we'll check it together!

**Comment by nihirash** [comment]
Did it helped?

**Comment by appndownUG** [comment]
Yes, this help.
Now it run.
